# Лабораторная работа 0
Numpy

Выполнил: 6306, Бамбурова Мария Владимировна

Лабораторная работа не обязательна для выполнения, но рекомендуется для тех, кто не знаком с библиотекой numpy и работой с многомерными массивами.

1 Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать их работу. Для каждой функции добавить комментарий.

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
ФУНКЦИИ

In [ ]:

#1)type(numpy.ndarray)
#Это функция Python, используемая, чтобы вернуть тип переданного параметра. В случае с массивом numpy, она вернет numpy.ndarray.
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#2)numpy.zeroes()
#numpy.zeros((rows, columns), dtype)
#Эта функция создаст массив numpy с заданным количеством измерений, где каждый элемент будет равняться 0.
#Если dtype не указан, по умолчанию будет использоваться dtype.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#3)numpy.ones()
#numpy.ones((rows,columns), dtype)
#Эта функция создаст массив numpy с заданным количеством измерений, где каждый элемент будет равняться 1.
#Если dtype не указан, по умолчанию будет использоваться dtype.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#4)numpy.empty()
#numpy.empty((rows,columns))
#Эта функция создаст массив, содержимое которого будет случайным — оно зависит от состояния памяти.
np.empty((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#5)numpy.arrange()
#numpy.arrange(start, stop, step)
#Эта функция используется для создания массива numpy,
#элементы которого лежат в диапазоне значений от start до stop с разницей равной step.
a=np.arange(5,25,4)
print(a)

[ 5  9 13 17 21]


In [ ]:
#6)numpy.linspace()
#numpy.linspace(start, stop, num_of_elements)
#Эта функция создаст массив numpy, элементы которого лежат в диапазоне значений между start до stop, а num_of_elements — это размер массива.
#Тип по умолчанию — float64.
import numpy as np
a=np.linspace(5,25,5)
print(a)

[ 5. 10. 15. 20. 25.]


In [ ]:
#7)numpy.logspace()
#numpy.logspace(start, stop, num_of_elements)
#Эта функция используется для создания массива numpy, элементы которого лежат в диапазоне значений от start до stop,
#а num_of_elements — это размер массива.
#Тип по умолчанию — float64.
#Все элементы находятся в пределах логарифмической шкалы, то есть представляют собой логарифмы соответствующих элементов.
a = np.logspace(5,25,5)
print(a)

[1.e+05 1.e+10 1.e+15 1.e+20 1.e+25]


In [ ]:
#8)numpy.sin()
#numpy.sin(numpy.ndarray)
#Этот код вернет синус параметра.
a = np.logspace(5,25,2)
print(np.sin(a))

[ 0.0357488 -0.3052578]


In [ ]:
#9)numpy.reshape()
#numpy.reshape(dimensions)
#Эта функция используется для изменения количества измерений массива numpy.
#От количества аргументов в reshape зависит, сколько измерений будет в массиве numpy.
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10)numpy.random.random()
#numpy.random.random((rows, column))
#Эта функция возвращает массив с заданным количеством измерений, где каждый элемент генерируется случайным образом.
a = np.random.random((2,2))
print(a)

[[0.48891969 0.99407646]
 [0.83281596 0.43068855]]


In [ ]:
#11)numpy.exp()
#numpy.exp(numpy.ndarray)
#Функция вернет ndarray с экспоненциальной величиной каждого элемента.
b = np.exp([10])
print(b)

[22026.46579481]


In [ ]:
#12)numpy.sqrt()
#numpy.sqrt(numpy.ndarray)
#Эта функция вернет ndarray с квадратным корнем каждого элемента.
b = np.sqrt([16])
print(b)

[4.]


2 Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам.
Оси:
    0: ID группы товаров
    1: ID магазина
    2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц).

Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

Рекомендуется сгенерировать статистически-правдопододные данные в ячейках.
К примеру, будет странно, если продажи одной и той же группы товаров в соседние дни будут представлять из себя "белый шум". Пусть будет какой-то правдоподобное распределение на ваш вкус.
Также продажи одних и тех же групп товаров в разных магазинах не могут отличаться в сотни и тысячи раз, максимум в разы.
Подумайте как это обыграть используя различные функции генерации случайных чисел + "смекалку".

In [ ]:
import numpy as np
import random
products = np.arange(0, 22, 1)
shops = np.arange(0, 5, 1)
days = np.arange(1, 31, 1)
cube = np.zeros([products.size, shops.size, days.size])

for p in range(products.size):
  for s in range(shops.size):
    for d in range(days.size):
      cube[p, s, d] = np.random.randint(10, 80)

print(cube)


[[[61. 54. 71. ... 44. 69. 35.]
  [77. 76. 33. ... 46. 13. 25.]
  [64. 38. 75. ... 18. 44. 32.]
  [54. 71. 41. ... 61. 70. 19.]
  [27. 13. 44. ... 57. 21. 52.]]

 [[54. 43. 31. ... 67. 69. 36.]
  [53. 37. 22. ... 71. 18. 60.]
  [21. 28. 15. ... 32. 42. 18.]
  [19. 59. 28. ... 57. 69. 41.]
  [30. 17. 58. ... 62. 32. 43.]]

 [[14. 39. 30. ... 69. 23. 20.]
  [74. 40. 78. ... 55. 53. 75.]
  [26. 51. 21. ... 40. 28. 55.]
  [47. 47. 52. ... 41. 28. 13.]
  [59. 74. 71. ... 28. 39. 66.]]

 ...

 [[72. 36. 42. ... 63. 19. 76.]
  [34. 61. 24. ... 49. 75. 26.]
  [26. 44. 42. ... 18. 38. 37.]
  [47. 21. 28. ... 78. 43. 26.]
  [36. 45. 31. ... 71. 79. 41.]]

 [[63. 19. 36. ... 11. 47. 24.]
  [49. 41. 52. ... 58. 13. 22.]
  [45. 18. 75. ... 21. 10. 31.]
  [56. 66. 50. ... 42. 35. 53.]
  [77. 79. 53. ... 12. 20. 24.]]

 [[53. 25. 76. ... 12. 16. 41.]
  [66. 60. 31. ... 63. 34. 79.]
  [24. 25. 77. ... 61. 35. 15.]
  [39. 29. 15. ... 17. 49. 17.]
  [41. 40. 63. ... 11. 23. 70.]]]


3 Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать)зафиксировав значения по одной, двум или трём осям:

Например взять какой-то определённый набор товаров и набор городов или диапазон дней и сагрегировать данные по всем ячейкам из зафиксированного набора.
Пример: получить сумму, среднее, минимум и максимум по продажам 10-20 чисел месяца для товаров [1,3,4] по всем городам (или по конкретному набору городов).

Попробуйте различные варианты индексации и различные варианты срезов, насколько хватит фантазии.

In [ ]:
 print("Общая сумма продаж всех товаров во всех магазинах за весь месяц: \n")
print(np.sum(cube[:,:,:]))
print("\n-----------------------------------------------------\n")

print("Сумма по продажам 1-5 чисел месяца для товара 9 по всем магазинам: \n")
print(np.sum(cube[9,:,[days[0:5]]]))
print("\n-----------------------------------------------------\n")

print("Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: \n")
print(np.min(cube[16,3,[days[9:20]]]))
print("\n-----------------------------------------------------\n")

print("Минимум по продажам 15-20 чисел месяца для товара 9 в магазине 2: \n")
print(np.min(cube[9,2,[days[14:20]]]))
print("\n-----------------------------------------------------\n")

print("Стандартное отклонение по продажам 1-10 чисел месяца для товара 1 по всем магазинам: \n")
print(np.std(cube[1,:,[days[0:10]]]))
print("\n-----------------------------------------------------\n")


print("Максимум по продажам за все время для товара 12 в магазине 2: \n")
print(np.max(cube[12,2,:]))
print("\n-----------------------------------------------------\n")

print("Cреднее по продажам за все время для товара 1 в магазине 1: \n")
print(np.mean(cube[1,1,:]))
print("\n-----------------------------------------------------\n")




Общая сумма продаж всех товаров во всех магазинах за весь месяц: 

147684.0

-----------------------------------------------------

Сумма по продажам 1-5 чисел месяца для товара 9 по всем магазинам: 

944.0

-----------------------------------------------------

Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: 

12.0

-----------------------------------------------------

Минимум по продажам 15-20 чисел месяца для товара 9 в магазине 2: 

22.0

-----------------------------------------------------

Стандартное отклонение по продажам 1-10 чисел месяца для товара 1 по всем магазинам: 

19.236465371788032

-----------------------------------------------------

Максимум по продажам за все время для товара 12 в магазине 2: 

79.0

-----------------------------------------------------

Cреднее по продажам за все время для товара 1 в магазине 1: 

42.06666666666667

-----------------------------------------------------



![olap-cube](http://www.olap.ru/basic/img/alpero2i2.gif)